# .pre-commit-config.yaml
# pre-commit does not support "rev: stable" properly; run "pre-commit autoupdate" to fix it.
default_stages: [commit, merge-commit, push, manual]
default_install_hook_types: [pre-commit, pre-merge-commit, pre-push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: detect-private-key
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
